### PR TITLE
Address type piracy compilation failures (fix #120)

### LINKED ISSUE #120: Precompilation error in 1.10: conflict with static arrays
It appears that  ChainRules v1.58.1 and TemporalGPs v0.6.5 both define adjoints for static arrays.
Loading static arrays, chain rules, and temporalGPs in one session results in:

``julia
WARNING: Method definition rrule(Type{T}, Tuple) where {T<:(StaticArraysCore.SArray{S, T, N, L} where L where N where T where S<:Tuple)} in module StaticArraysChainRulesCoreExt at /Users/thompsonw/.julia/packages/StaticArrays/Uc4hE/ext/StaticArraysChainRulesCoreExt.jl:26 overwritten in module TemporalGPs at /Users/thompsonw/.julia/packages/TemporalGPs/zMIeA/src/util/chainrules.jl:31.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
```

The two conflicting definitions appear to be:
```julia
function rrule(::Type{T}, x::Tuple) where {T <: SArray}
    project_x = ProjectTo(x)
    ∇Array(∂y) = (NoTangent(), project_x(∂y))
    return T(x), ∇Array
end
```
in ChainRules

and 
```julia
function rrule(::Type{T}, x::Tuple) where {T<:SArray}
    SArray_rrule(Δ) = begin
        (NoTangent(), Tangent{typeof(x)}(unthunk(Δ).data...))
    end
    return T(x), SArray_rrule
end
```
in TemporalGPs.

### PR DESCRIPTION
**Pull request by sefffal**
This PR just removes some apparently unneeded diff rules that pirated static arrays.
Running ]test TemporalGPs passes after removing these lines.

### CODE REVIEW

**Comment by sefffal** [comment]
cc @willtebbutt

**Comment by sefffal** [comment]
Hi all, I know there is work on a migration to Enzyme, but in the meantime could we look at merging this PR or similar? I'm still getting compilation errors in OctofitterRadialVelocity on 1.10 due to this issue.

Thanks for your help!

**Comment by willtebbutt** [comment]
Hi @sefffal  -- sorry for dropping this. I'm just running CI again to see if the tests start passing. I'm happy to merge if they do, and to assist debugging if they don't. I agree that it would be good to get this sorted.

**Comment by sefffal** [comment]
@willtebbutt thanks so much! It's no problem, I have a mountain of OSS issues to tackle myself ;) 

It looks like my changes were a little over broad and causing failures, we might need to be more surgical and just remove the one offending method.

**Comment by willtebbutt** [comment]
Closing as this is now outdated. Please feel free to re-open if you feel there's more to be done.

**Pull request closed without merging**
