### PR TITLE
[WIP, not to merge] Migrate to Enzyme

### PR DESCRIPTION
**Pull request by simsurace**
The library is getting hard to maintain mainly because of the way it works around Zygote limitations, which is by using a lot of hacks and type piracy that are relying on various package internals and are therefore prone to breakage.
This is a draft to migrate to Enzyme and getting rid of all AD-specific hacks.
TODOs:
- [ ] Make examples run with Enzyme
- [ ] Add integration tests for AD to cover all input types and kernels.

### CODE REVIEW

**Comment by simsurace** [comment]
The first example, exact time learning, now runs on Enzyme. There might be a bug still in Enzyme, which is why the shadows wrt. the inputs are needed right now.

**Comment by willtebbutt** [comment]
@simsurace are you still interested in this? I've recently excised basically all of the AD-related code in favour of just using Mooncake.jl, so I imagine you would just need to check that Enzyme successfully runs on some high-level examples?

**Comment by simsurace** [comment]
Hi, nice work on Mooncake and great that we have another option now. I'm still interested but since my work currently does not need GPs I have had to set these interests somewhat aside. I will almost certainly be using GPs again sooner or later so I hope JuliaGPs lives on.

**Comment by willtebbutt** [comment]
Thanks @simsurace. In this case I'm going to close this PR for the time being, as I suspect that things have moved on quite a bit since you were attempting to get it to work. Please feel free to reopen at some point in future if you start using GPs again!

**Pull request closed without merging**
